---

- name: 'Install Grafana Loki'
  hosts: 'k3s1'
  gather_facts: true
  become: false
  module_defaults:
    kubernetes.core.helm:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s_info:
      kubeconfig: './k3s-kubeconfig'

  tasks:

    - name: 'Install Grafana Loki via the helm chart'
      kubernetes.core.helm:
        chart_repo_url: 'https://grafana.github.io/helm-charts'
        release_name: 'loki'
        chart_ref: 'loki'
        release_namespace: 'grafana-loki'
        release_values:
          write:
            affinity: null
          read:
            affinity: null
          backend:
            affinity: null
          chunksCache:
            enabled: false
          loki:
            auth_enabled: false
            useTestSchema: true
            storage:
              bucketNames:
                chunks: chunks
                ruler: ruler
                admin: admin
              type: s3
              s3:
                endpoint: minio
                secretAccessKey: minio-vagrant-libvirt-user
                accessKeyId: secret123
                s3ForcePathStyle: false
                insecure: true
      delegate_to: 'localhost'

    - name: 'Wait until all pods are running'
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: grafana-loki
      register: pod_list
      until:
        '
        pod_list | json_query("resources[*].status.phase") | unique == ["Running"]
        or
        pod_list | json_query("resources[*].status.phase") | unique == ["Running", "Succeeded"]
        '
      retries: 12
      delay: 10
      delegate_to: 'localhost'
